E4BigSchool/Controllers/CoursesController.cs
using E4BigSchool.Models;
using E4BigSchool.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E4BigSchool.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }
        // GET: Courses
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
            };
            return View(viewModel);
        }
    }
}

E4BigSchool/Views/Courses/Create.cshtml
@model E4BigSchool.ViewModels.CourseViewModel

@{
        ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<form>
    @using (Html.BeginForm("Create", "Courses"))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Place)
            @Html.TextBoxFor(m => m.Place, new { @Class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @Class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @Class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Category)
            @Html.DropDownListFor(m => m.Category,
                new SelectList(Model.Categories, "Id", "Name"), "", new { @Class = "form-control" })
        </div>
        <br />
        <button type="submit" value="Save" class="btn btn-success">Save</button>
        <div class="form-group"></div>
        <div class="form-group"></div>
    }
</form>